#!/bin/bash

# Setup repo store folder
cd "/home/$USER"
mkdir .htt
cd .htt

# Get repository from url
git clone https://github.com/TomascpMarques/Html-Template-Transpiler.git

# Move to project folder
cd 'Html-Template-Transpiler'

# Give execution permition
chmod +x htt

# Make available from everywher
sudo cp htt /usr/bin/
